name: Checkmarx Scan

on:
  push:
    branches:
      - main  # Adjust these branches as necessary

jobs:
  checkmarx_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Checkmarx CLI
        run: |
          # Descargo el archivo .tar.gz 
          curl -L "https://github.com/Checkmarx/ast-cli/releases/download/2.0.74/ast-cli_2.0.74_linux_x64.tar.gz" -o cx.tar.gz
          # Extraigo archivo y lo llevo a /usr/local/bin
          tar -zxvf cx.tar.gz -C /usr/local/bin
          # Permisos de ejecucion
          chmod +x /usr/local/bin/cx
          # Verify the installation
          /usr/local/bin/cx version

      - name: Run Checkmarx Scan
        env:
          CHECKMARX_HOST: ${{ secrets.CHECKMARX_HOST }}
          CHECKMARX_API_KEY: ${{ secrets.CHECKMARX_API_KEY }}
        run: |
          echo "Starting Checkmarx scan..."
          # Use GitHub's repository name for the Checkmarx project name
          PROJECT_NAME="${GITHUB_REPOSITORY}" 
          echo "Using project name: $PROJECT_NAME"
          ABSOLUTE_PATH=$(pwd)
          /usr/local/bin/cx scan create --project-name "$PROJECT_NAME" -s "$ABSOLUTE_PATH" --base-auth-uri "$CHECKMARX_HOST" --apikey "$CHECKMARX_API_KEY" --debug --branch main
          echo "Scan complete."
