name: Checkmarx Scan

on:
  push:
    branches:
      - main  # Adjust these branches as necessary

jobs:
  checkmarx_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Checkmarx CLI
        run: |
          # Download the .tar.gz archive
          curl -L "https://github.com/Checkmarx/ast-cli/releases/download/2.0.74/ast-cli_2.0.74_linux_x64.tar.gz" -o cx.tar.gz
          # Extract the archive using tar
          tar -zxvf cx.tar.gz -C /usr/local/bin
          # Assuming the executable is directly in the tar.gz root and is named 'cx'
          chmod +x /usr/local/bin/cx
          # Verify the installation
          /usr/local/bin/cx version

      - name: Run Checkmarx Scan
        env:
          CHECKMARX_HOST: ${{ secrets.CHECKMARX_HOST }}
          CHECKMARX_API_KEY: ${{ secrets.CHECKMARX_API_KEY }}
        run: |
          echo "Starting Checkmarx scan..."
          # Use GitHub's repository name for the Checkmarx project name
          PROJECT_NAME="${GITHUB_REPOSITORY}"  # This strips any owner prefix to just use the repo name
          echo "Using project name: $PROJECT_NAME"
          # Insert the Checkmarx scan command, ensuring to use the PROJECT_NAME
          # Replace the placeholder with the actual command according to your Checkmarx setup
          /usr/local/bin/cx scan create --project-name "$PROJECT_NAME" --sources './' --cx-server "$CHECKMARX_HOST" --api-key "$CHECKMARX_API_KEY" --verbose
          echo "Scan complete."
